### ISSUE TITLE
concurrent-ruby gem depenency

### ISSUE THREAD

**Issue by jpserra** [launchdarkly/ruby-client#115]
Hello there, 

I'm trying to use the ldclient-rb gem but I'm fighting some gem dependencies here, and I realised that `ldclient-rb` requires `concurrent-ruby` to be under `1.1`. Any change this is just _"legacy"_ or it can be updated on launchdarkly ruby client?

**Comment by eli-darkly** [comment]
Ugh - yes, that looks like it's just a legacy mistake. Thanks for pointing it out. We'll get a patch release out ASAP with less strict dependencies.

**Comment by eli-darkly** [comment]
We've updated the dependencies in the 5.4.2 release. Please let us know if this works for you.

**Comment by jpserra** [comment]
Thank you for addressing this so quickly 👍
