### ISSUE TITLE
DynamoDB feature store support

### ISSUE THREAD

**Issue by Vlaaaaaaad** [launchdarkly/ruby-client#119]
For serverless usecases [DynamoDB was implemented as a feature store state in the Go, Java, .NET and Node SDKs](
https://docs.launchdarkly.com/v2.0/docs/using-a-persistent-feature-store#section-using-dynamodb).

Creating this issue to express interest in supporting DynamoDB feature store in the Ruby SDK too.

**Comment by eli-darkly** [comment]
Yes, it's been our intention to add the same support to all of the server-side SDKs. Ruby support should be released pretty soon.

**Comment by eli-darkly** [comment]
OK! DynamoDB support is now included in the latest release. The documentation at the link above has been updated.

We've also greatly improved our documentation comments, so the generated API documentation at https://www.rubydoc.info/gems/ldclient-rb should _eventually_ be more useful. However, at the moment, that site appears to be lagging and isn't yet showing the latest docs. Hopefully it will catch up soon.
