### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by ukd1** [launchdarkly/ruby-client#21]
Are you planning on writing tests?

**Comment by jkodumal** [comment]
We have a fairly extensive integration test suite for our all our SDKs. We've built reference applications for each SDK, all hosted on Heroku. Each reference app exposes each method in the SDK via a REST API. A central integration harness then drives each reference app via that API, and verifies its behavior. As compared to unit tests, this approach lets us:

* Verify that every SDK behaves identically, ensuring that the targeting and rollout algorithms are implemented to the same specification-- super important if you have a polyglot stack.

* Ensures end-to-end processing of analytics events.

* Ensures that our SDKs recover from network issues appropriately.

While these tests give us confidence that our SDKs match our reference implementation, and behave correctly in real-world conditions, it is a little difficult for us to provide visibility into these results, so we will be implementing unit tests as well. 

Hope this gives you some more confidence in our testing procedures, and thanks for the feedback!

**Comment by albertyw** [comment]
The rspec tests are now at ~85% test coverage according to ruby's `simplecov` gem, not including the integration tests.  The remaining 15% of lines are either trivial functions or extremely hard to unit test code which are covered by integration tests.
