### ISSUE TITLE
Retrieve list of all features rolled out for a particular key

### ISSUE THREAD

**Issue by sgringwe** [launchdarkly/ruby-client#62]
Is there a way to get a list of all the features enabled for a given user/key? Just a list of enabled feature keys would work perfectly.

**Comment by sgringwe** [comment]
Thanks @jkodumal . Is there any documentation on that method? Is this going to LD servers for every flag?

**Comment by jkodumal** [comment]
@sgringwe -- it's something we've been slowly rolling out to all our SDKs, so it hasn't been documented yet. If streaming is enabled, this will evaluate all flags for the provided user from the flag rules stored in memory, so it will not make a remote call. If streaming is disabled, this will make a remote HTTP request, though will still use local HTTP cache if your TTL is set to non-zero. 

It will return a hash of symbolized feature flag keys to flag values.

**Comment by sgringwe** [comment]
@jkodumal yes, that works. it'd be great to see this feature made more public in the api and to make sure any changes are mentioned in CHANGELOG. thanks!

**Comment by jkodumal** [comment]
Definitely @sgringwe -- we're waiting on a couple things before we announce this more publicly:

1) A strategy for sending events back to LD when you call this method. At the moment, calling this won't send analytics data back to LD, so you won't see these events on your dev console.

2) Full support across all our SDKs

This method is stable-- we're not going to change the API, so you can use it in production, but just wanted to make you aware especially of the analytics limitation.

**Comment by sgringwe** [comment]
@jkodumal thanks. we use it for tracking in intercom, full story, etc. what features they have turned on.

**Comment by sgringwe** [comment]
@jkodumal hmm it looks like this method was removed in the latest version. is there a new alternative?

**Comment by jkodumal** [comment]
Hi @sgringwe -- for consistency with our other SDKs the method has been renamed to `all_flags`-- it should behave equivalently.
