### ISSUE TITLE
Intermittent 'too many connection resets' error

### ISSUE THREAD

**Issue by drichelson** [launchdarkly/ruby-client#64]
[LDClient] Unexpected exception in create_worker: # too many connection resets (due to Net::ReadTimeout - Net::ReadTimeout)

This is happening when posting events. It is possibly related to this issue: http://stackoverflow.com/questions/35876658/too-many-connection-resets-exception-error-mechanize-in-ruby

**Comment by sgringwe** [comment]
Any update on this? We are getting this error very consistently now.

**Comment by jkodumal** [comment]
@sgringwe We're still investigating, and are actively trying to reproduce this in our environment. 

One thing we noted is that that the SO post @drichelson linked is only relevant if `net_http_persistent` is in use, which is not the case when posting events.

**Comment by jkodumal** [comment]
We believe we were seeing occasionally poor DNS lookup times from Route 53. We did some load testing and found occasional requests with 5+ second DNS resolution times. We increased our DNS TTL, and this appears to have resolved the issue.
