### ISSUE TITLE
Client fails to receive updates in Rails console if Spring is enabled

### ISSUE THREAD

**Issue by jkodumal** [launchdarkly/ruby-client#73]
If Spring is enabled, the LaunchDarkly client does not receive feature flag updates in the rails console. A workaround is to disable Spring:

`DISABLE_SPRING=true rails console`

**Comment by justinucd** [comment]
Update: To use LaunchDarkly with the Rails application preloader Spring, we recommend using an `after_fork` callback in the config/spring.rb file.

[Code example and documentation](http://docs.launchdarkly.com/v2.0/docs/ruby-sdk-reference#initializing-ldclient-using-spring)

**Comment by robwise** [comment]
@justinucd If we are using both Spring _and_ Puma with our Rails app, which method should we use (Puma after_boot or Spring after_fork)?

**Comment by markedmondson** [comment]
@robwise you should be good in the `Spring#after_fork`

**Comment by justinucd** [comment]
Thanks @markedmondson !  @robwise let me know if this works for you - if not, we can look into it further

**Comment by robwise** [comment]
So do I have to put some sort of conditional in there based on the environment? Because we don't run spring in production, just when running our test suites, so launchdarkly would never get initialized in those cases. So do I also start it via Puma as well?

**Comment by markedmondson** [comment]
Semi-pseudo code:

```
LaunchDarklyInitializer = lambda do
  LaunchDarkly::LDClient.new...
end

if defined?(Spring)
  Spring.after_fork do
    LaunchDarklyInitializer.call
  end
else
  LaunchDarklyInitializer.call
end
```
