### ISSUE TITLE
Broken lib ldclient.min.js

### ISSUE THREAD

**Issue by isavita** [launchdarkly/ruby-client#77]
If I download *ldclient.min.js* from the following link https://app.launchdarkly.com/snippet/ldclient.min.js. I am getting this error https://github.com/launchdarkly/js-client/issues/29. Is this still an issue?

**Comment by jkodumal** [comment]
Hi @isavita --

The CDN hosted file (ldclient.min.js) wasn't updated to the latest js-client version (1.1.4). We'll be deploying the update shortly.

Thanks for the report!

**Comment by jkodumal** [comment]
A newer version has been deployed-- this should be fixed now.

Thanks again!
