### ISSUE TITLE
Updates stop working after some time

### ISSUE THREAD

**Issue by aserafin** [launchdarkly/ruby-client#81]
Hi, 

I have issue with your latest gem release

````
gem 'ldclient-rb', '2.0.5'
gem 'ld-celluloid-eventsource', '0.8.3'
````

what I'm seeing is that is starts working correctly, I'm getting information about waiting for heartbeats for 300s, I can see messages when I change flag value from the ui but after some time I get this in logs

````
[EventSource] Didn't get heartbeat after 300 seconds. Reconnecting.
````

and after this message none of the changes made in ui are passed to the application. I have to restart entire ruby process to make it work again. 

I'm not seeing this issue with this combination

````
gem 'ldclient-rb', '2.0.3'
gem 'ld-celluloid-eventsource', '0.5.0'
````

but I've noticed that a lot off stuff changed regarding `ld-celluloid-eventsource` between the releases.

**Comment by drichelson** [comment]
@aserafin Thanks for reaching out. Do you mind emailing support@launchdarkly.com and we can continue troubleshooting there?

**Comment by drichelson** [comment]
Conversation switched to support@launchdarkly.com. Closing this issue

**Comment by aserafin** [comment]
@drichelson you said on the support email that this problem is happening to you and that you were working on a fix but not messages from you since. Could you please get back to me on that topic?

**Comment by atrakh** [comment]
Hey @aserafin - the Ruby SDK has since been updated. Are you still experiencing this issue on ruby-client versions >= 2.1.0?

**Comment by aserafin** [comment]
@atrakh it looks like we still have this issue - we should be getting around with updating to the latest client version that hopefully will solve it but if not I will post here so maybe you can reopen again.

**Comment by atrakh** [comment]
Hi @aserafin - thanks for the update. 

I'm reopening this ticket so that we can pick up where we left off. Let us know if you still run into this issue after updating your client.
