### ISSUE TITLE
Not compatible with Rails 5.1

### ISSUE THREAD

**Issue by sgringwe** [launchdarkly/ruby-client#83]
When specifying `gem 'rails', '~> 5.1.0.rc1'` and the latest ld ruby gem, the following incompatibility is met:

```
Bundler could not find compatible versions for gem "nio4r":
  In Gemfile:
    rails (~> 5.1.0.rc1) was resolved to 5.1.0.rc1, which depends on
      actioncable (= 5.1.0.rc1) was resolved to 5.1.0.rc1, which depends on
        nio4r (~> 2.0)

    ldclient-rb (= 2.0.6) was resolved to 2.0.6, which depends on
      nio4r (~> 1.1)
:
```

**Comment by jkodumal** [comment]
Hey @sgringwe thanks for the report -- looks like a transitive dependency conflict. We'll take a look and see if we can resolve it on our end.

**Comment by adamlaunchingdarkly** [comment]
Scott - thanks for reporting this.  We will look into it!

**Comment by adamlaunchingdarkly** [comment]
@sgringwe - We have just release version 2.1.1 as a fix.  Thank you for reporting this!

**Comment by sgringwe** [comment]
@adamlaunchingdarkly 🤔  I'm not seeing 2.1.1 on rubygems.org?

**Comment by adamlaunchingdarkly** [comment]
@sgringwe - just bumped to 2.1.5.  Please let me know if you run into any issues.
